version: "3"

services:
  # https-portal:
  #   image: steveltn/https-portal:1
  #   container_name: server
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   environment:
  #     DOMAINS: "www.hk-41.work -> http://frontend:81"
  #     STAGE: "production"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/prod/Dockerfile
      args:
        REACT_APP_MODE: $REACT_APP_MODE
    ports:
      - "80:80"
    # environment:
    #   - REACT_APP_MODE=prod
    restart: always
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/prod/Dockerfile
    ports:
      - "82:80"
    environment:
      - DJANGO_APP_MODE=prod
    restart: always
