version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/dev/Dockerfile
      args:
        REACT_APP_MODE: $REACT_APP_MODE
    ports:
      - "81:3000"
    volumes:
      - ./frontend:/app
    # environment:
    #   - REACT_APP_MODE=dev
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/dev/Dockerfile
    command: python ./backend/manage.py runserver 0.0.0.0:8000
    ports:
      - "82:8000"
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_APP_MODE=dev
