version: "3"

services:
  https-portal:
    image: steveltn/https-portal:1
    container_name: server
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: "www.hk-41.work -> http://frontend:82"
      STAGE: "production"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/prod/Dockerfile
    ports:
      - "82:80"
    restart: always
