version: "3"

services:
  https:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      STAGE: local
      DOMAINS: "www.dev.localhost -> http://proxy:81"
  proxy:
    image: nginx:latest
    ports:
      - "81:81" # ブラウザからは localhost:<前のポート番号> でアクセスする
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d
    restart: always
  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/dev/Dockerfile
      args:
        REACT_APP_MODE: $REACT_APP_MODE
    # ports:
    #   - "3000:3000"
    volumes:
      - ./frontend:/app
    # environment:
    #   - REACT_APP_MODE=dev
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/dev/Dockerfile
    command: python ./backend/manage.py runserver 0.0.0.0:8000
    # ports:
    #   - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_APP_MODE=dev
